name = "Spinners"
uuid = "28ab5b7a-bdcc-4f1e-a5de-638613dcf356"
authors = ["Ashlin Harris <ashlin_harris@brown.edu>"]
version = "0.1.0"

[deps]
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
