name = "Spinners"
uuid = "28ab5b7a-bdcc-4f1e-a5de-638613dcf356"
authors = ["Ashlin Harris <ashlin_harris@brown.edu>"]
version = "0.5.1"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
julia = "^1.8"
