name = "Spinners"
uuid = "28ab5b7a-bdcc-4f1e-a5de-638613dcf356"
authors = ["Ashlin Harris <ashlin_harris@brown.edu>"]
version = "0.3.0"

[deps]
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
julia = "^1.2"

